# Regression

### import required packages

In [1]:
from pickletools import optimize

import numpy as np
import torch

### Generate the data

In [2]:
# independent variable
x = torch.tensor([[1.], [2.], [3.], [4.], [5.], [6.], [7.], [8.], [9.], [10.]])

# dependent variable
# y = 2x + 1
y = torch.tensor([[3.], [5.], [7.], [9.], [11.], [13.], [15.], [17.], [19.], [21.]])

### define the hyperparameters

In [3]:
# create the model
# note : linear is layer which has  input and putput
# - this model represents a perceptron
model = torch.nn.Linear(in_features=1,out_features=1)

In [4]:
model

Linear(in_features=1, out_features=1, bias=True)

In [5]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4631]], requires_grad=True),
 Parameter containing:
 tensor([0.6340], requires_grad=True)]

In [6]:
# number of epochs
epochs = 100

# learning rate to adjust the parameters
learning_rate = 0.01

#loss function
loss_function = torch.nn.MSELoss()

# optimizer used to optimize the model parameters (Weight and bias)
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

### training loop

In [7]:
for epoch in range(epochs):

    # forward propagation
    y_hat = model(x)

    # calculate the loss
    loss = loss_function(y_hat,y)

    # zero out the optimizer before calculating the gradients
    optimizer.zero_grad()

    #calculate the loss gradients
    loss.backward()

    #optimize the weight and bias (model parameters)
    optimizer.step()

In [8]:
list(model.parameters())

[Parameter containing:
 tensor([[2.0011]], requires_grad=True),
 Parameter containing:
 tensor([0.9921], requires_grad=True)]

### Model Inference

In [9]:
# inference the leraning for the x =11
model(torch.tensor([[11.0]]))

tensor([[23.0046]], grad_fn=<AddmmBackward0>)